import type { Metadata } from 'next';
import Link from 'next/link';
import { AlertTriangle, ArrowLeft, Bot, CheckCircle2, FileText, KeyRound, Send, ShieldCheck, Sparkles, Webhook } from 'lucide-react';
import { Button } from '@/components/ui/button';

export const metadata: Metadata = {
  title: 'Documentation',
  description: 'NexusAI documentation for secure webhooks, Telegram Bot connections, content generation, publishing, and acceptable use.',
};

const navigation = [['overview', 'Overview'], ['webhooks', 'Webhooks'], ['telegram', 'Telegram Bot'], ['publishing', 'Publishing'], ['safety', 'Content Safety']] as const;

function Step({ number, title, children }: { number: number; title: string; children: React.ReactNode }) {
  return <li className="flex gap-4"><span className="flex h-7 w-7 shrink-0 items-center justify-center rounded-full border border-cyan-400/30 bg-cyan-400/10 text-xs font-bold text-cyan-300">{number}</span><div><h3 className="text-sm font-semibold text-white">{title}</h3><div className="mt-1 text-xs leading-6 text-slate-400">{children}</div></div></li>;
}

export default function DocsPage() {
  return <div className="min-h-screen bg-[hsl(220,16%,6%)] text-slate-100">
    <header className="sticky top-0 z-20 border-b border-slate-800 bg-slate-950/90 backdrop-blur-xl"><div className="mx-auto flex max-w-7xl items-center justify-between px-4 py-4 sm:px-6"><Link href="/" className="flex items-center gap-2 font-semibold"><span className="flex h-8 w-8 items-center justify-center rounded-lg bg-gradient-to-br from-cyan-400 to-blue-500"><Sparkles className="h-4 w-4 text-slate-950" /></span>NexusAI Docs</Link><Button asChild variant="ghost"><Link href="/"><ArrowLeft className="mr-2 h-4 w-4" />Back to Home</Link></Button></div></header>
    <div className="mx-auto grid max-w-7xl gap-8 px-4 py-10 sm:px-6 lg:grid-cols-[220px_minmax(0,1fr)]">
      <aside className="lg:sticky lg:top-24 lg:h-fit"><p className="mb-3 text-[10px] font-semibold uppercase tracking-[0.2em] text-slate-500">On this page</p><nav className="flex gap-2 overflow-x-auto lg:flex-col">{navigation.map(([id, label]) => <a key={id} href={`#${id}`} className="whitespace-nowrap rounded-lg px-3 py-2 text-xs text-slate-400 hover:bg-white/5 hover:text-cyan-300">{label}</a>)}</nav><div className="mt-6 hidden rounded-xl border border-cyan-400/15 bg-cyan-400/5 p-3 text-[11px] leading-5 text-slate-400 lg:block"><ShieldCheck className="mb-2 h-4 w-4 text-emerald-400" />Never paste service credentials into prompts, generated content, or public support messages.</div></aside>
      <main className="min-w-0 space-y-10">
        <section id="overview" className="scroll-mt-28"><p className="text-xs font-semibold uppercase tracking-[0.2em] text-cyan-400">Help center</p><h1 className="mt-3 text-3xl font-bold sm:text-4xl">NexusAI Automation Documentation</h1><p className="mt-4 max-w-3xl text-sm leading-7 text-slate-400">Generate an audited content package, review every claim and channel variant, then deliberately queue it for a connected website or social destination. Successful generations are saved to Content History, while the active package remains visible as you move between dashboard pages.</p><div className="mt-6 grid gap-3 sm:grid-cols-3"><div className="rounded-xl border border-slate-800 bg-slate-900/70 p-4"><FileText className="h-4 w-4 text-cyan-300" /><h2 className="mt-3 text-sm font-semibold">Generate</h2><p className="mt-1 text-xs leading-5 text-slate-500">Build blog, schema, social copy, and visuals.</p></div><div className="rounded-xl border border-slate-800 bg-slate-900/70 p-4"><CheckCircle2 className="h-4 w-4 text-emerald-300" /><h2 className="mt-3 text-sm font-semibold">Review</h2><p className="mt-1 text-xs leading-5 text-slate-500">Verify accuracy, rights, links, and brand tone.</p></div><div className="rounded-xl border border-slate-800 bg-slate-900/70 p-4"><Send className="h-4 w-4 text-violet-300" /><h2 className="mt-3 text-sm font-semibold">Publish</h2><p className="mt-1 text-xs leading-5 text-slate-500">Select an authorized destination and schedule.</p></div></div></section>

        <section id="webhooks" className="scroll-mt-28 rounded-2xl border border-slate-800 bg-slate-900/60 p-5 sm:p-7"><h2 className="flex items-center gap-2 text-xl font-bold"><Webhook className="h-5 w-5 text-cyan-400" />Connect and use HTTPS webhooks</h2><ol className="mt-6 space-y-5"><Step number={1} title="Create a receiving endpoint">Create a server endpoint on a domain you control. It must accept HTTPS POST requests containing JSON. Do not use localhost, private-network addresses, or HTTP in production.</Step><Step number={2} title="Add the asset">Open <Link href="/dashboard/assets" className="text-cyan-400 hover:underline">Asset Manager</Link>, enter the domain, select the CMS, paste the complete HTTPS webhook URL, and connect the asset.</Step><Step number={3} title="Verify signatures">When webhook signing is enabled, calculate an HMAC-SHA256 digest over the exact raw body using your shared secret. Compare it with <code>X-NexusAI-Signature</code> using a timing-safe comparison before parsing or publishing.</Step><Step number={4} title="Handle deliveries safely">Validate the package ID, deduplicate retries, publish only approved fields, return a 2xx response promptly, and log failures without logging secrets or unnecessary personal data.</Step><Step number={5} title="Queue from NexusAI">Generate and review a package, select <strong>Publish / Sync Content</strong>, choose Automated Webhook Trigger, set a future time, and queue it.</Step></ol><pre className="mt-6 overflow-x-auto rounded-xl border border-slate-800 bg-slate-950 p-4 text-[11px] leading-5 text-cyan-200">{'{\n  "event": "content.published",\n  "package_id": "uuid",\n  "content": { "title": "...", "html": "...", "schema_json": {} }\n}'}</pre></section>

        <section id="telegram" className="scroll-mt-28 rounded-2xl border border-slate-800 bg-slate-900/60 p-5 sm:p-7"><h2 className="flex items-center gap-2 text-xl font-bold"><Bot className="h-5 w-5 text-blue-400" />Connect a Telegram channel safely</h2><ol className="mt-6 space-y-5"><Step number={1} title="Create the bot with @BotFather">Open the verified <strong>@BotFather</strong> account in Telegram, run <code>/newbot</code>, and follow its prompts for a display name and unique username.</Step><Step number={2} title="Protect the bot token">BotFather returns an authentication token. Treat it like a password: do not place it in source code, screenshots, prompts, or chat messages. Revoke and replace it through BotFather immediately if exposed.</Step><Step number={3} title="Add the bot to your channel">Add the bot as a channel administrator with only the permission required to post messages. Avoid unrelated administrative permissions.</Step><Step number={4} title="Identify the destination">Use the public <code>@channel_username</code> when available. Private channels may require their numeric chat ID.</Step><Step number={5} title="Verify in NexusAI">Open <Link href="/dashboard/social-integrations" className="text-cyan-400 hover:underline">Social Integrations</Link>, enter the token and destination, then choose Verify and connect. NexusAI verifies both with Telegram and encrypts the token before storage.</Step></ol><div className="mt-6 flex gap-3 rounded-xl border border-amber-400/20 bg-amber-400/5 p-4 text-xs leading-5 text-amber-100/80"><KeyRound className="h-4 w-4 shrink-0 text-amber-300" />Anyone holding a bot token can control that bot. Disconnect the integration and rotate the token through BotFather if you suspect compromise.</div></section>

        <section id="publishing" className="scroll-mt-28 rounded-2xl border border-slate-800 bg-slate-900/60 p-5 sm:p-7"><h2 className="flex items-center gap-2 text-xl font-bold"><Send className="h-5 w-5 text-violet-400" />Review and publishing workflow</h2><ol className="mt-6 space-y-5"><Step number={1} title="Generate and inspect">Confirm the title, HTML, metadata, JSON-LD, images, social text, facts, and claims.</Step><Step number={2} title="Choose a destination">Use a verified asset webhook or connected LinkedIn/Telegram destination. Disabled destinations must be connected before selection.</Step><Step number={3} title="Schedule deliberately">Set the correct future date and time. The background worker processes only queued records matching their delivery type.</Step><Step number={4} title="Monitor and correct">Review Content History and destination logs. Remove or correct inaccurate publications promptly.</Step></ol></section>

        <section id="safety" className="scroll-mt-28 rounded-2xl border border-red-400/20 bg-red-400/5 p-5 sm:p-7"><h2 className="flex items-center gap-2 text-xl font-bold"><AlertTriangle className="h-5 w-5 text-red-400" />Forbidden automated generation</h2><p className="mt-3 text-sm leading-6 text-slate-400">Do not generate or automate content involving illegal activity, credible threats, exploitation, harassment, phishing, fraud, impersonation, fabricated reviews, deceptive endorsements, malware, credential theft, spam, privacy invasion, rights infringement, discriminatory high-impact decisions, or professional advice presented without qualified review. Do not fabricate sources, statistics, testimonials, product capabilities, or search-performance guarantees.</p><p className="mt-3 text-xs leading-5 text-slate-500">Users remain responsible for final review and compliance with the <Link href="/terms" className="text-cyan-400 hover:underline">Terms of Service</Link>, destination-platform rules, and applicable law.</p></section>
      </main>
    </div>
  </div>;
}
